version: 2

defaults: &defaults
  working_directory: ~/repo
  steps:
    - checkout

    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run: npm install
    - run:
        name: Run tests
        command: npm test

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - persist_to_workspace:
        root: ~/repo
        paths: .
jobs:
  test-node8:
    docker:
      - image: circleci/node:8.9.1
    <<: *defaults
  test-node10:
    docker:
      - image: circleci/node:10.16.0
    <<: *defaults
  test-node-latest:
    docker:
      - image: circleci/node:latest
    <<: *defaults
  deploy:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build Library
          command: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test-node8:
          filters:
            tags:
              only: /^v.*/
      - test-node10
      - test-node-latest:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test-node8
            - test-node10
            - test-node-latest
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
